[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm", "npx pnpm install --frozen-lockfile"]

[phases.build]
# Skip TypeScript checking for now and build directly with Vite
cmds = ["npx vite build"]

[start]
cmd = "npx pnpm preview --port $PORT --host 0.0.0.0"