[phases.setup]
nixPkgs = ["...", "nodejs_22"]

[phases.install]
cmds = ["corepack enable", "corepack prepare pnpm@latest --activate", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm preview --port $PORT --host 0.0.0.0"