[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm", "npx pnpm install --frozen-lockfile"]

[phases.build]
# Skip TypeScript checking for now and build directly with Vite
# Then copy module data files to dist for production serving
cmds = ["npx vite build", "mkdir -p dist/data", "cp -r src/data/modules dist/data/"]

[start]
cmd = "node server.cjs"